### ISSUE TITLE
希望能够精简回调结果定义

### ISSUE THREAD

**Issue by HubertZhang** [ant-mini-program/mini-types#16]
目前代码中在各处均出现了如下相同定义
```
success?():void
fail?():void
complete?():void
```
希望能使用范型和继承精简代码
```typescript
interface IAsyncFunctionalOptions<SuccessResult=any, FailResult=any> {
      /**
   * 调用成功的回调函数
   */
  success?(res: SuccessResult): void;

  /**
   * 调用失败的回调函数
   */
  fail?(res: FailResult): void;

  /**
   * 调用结束的回调函数（调用成功、失败都会执行）
   */
  complete?(res: any): void;
}

interface ISomeCallbackOptions extends IAsyncFunctionalOptions<ISomeSuccessResult>
```

**Comment by HubertZhang** [comment]
我自己尝试精简了一些，发现出现需要修改的地方太多，PR非常大，所以希望项目Owner能够主导一下这个改动哈

**Comment by yibuyisheng** [comment]
不好意思，最近有点忙，回复太晚。

关于这块的抽离，内部同学也做过相关讨论，当时考虑到“可读性”的问题，所以觉得抽离的价值不是很大，所以就搁置了。

具体“可读性”考量是这样的：
如果抽离，就会让类型代码复杂起来，涉及到泛型，用户过来阅读类型文件的时候，要了解某个 options 的全貌，就必须学习高阶类型知识，并做一个跳转操作。

mini-types 是小程序的一个辅助类型声明，并不会打包到最终的运行时代码中去，所以其实我们更关注的点是：
* 可读性；
* 类型提示的精确性。

所以在抽离类型的时候，我们不能破坏这两个原则。

（不过个人认为 success、fail、complete 这三个可以抽离^_^，但是优先级不是很高）
