### ISSUE TITLE
新增的一些api 没有定义

### ISSUE THREAD

**Issue by 18657769868** [ant-mini-program/mini-types#30]
比如 my.getExtConfigSync() 等还没有定义

**Comment by yibuyisheng** [comment]
@18657769868 好像官方 API 文档里面没看到。

**Comment by 18657769868** [comment]
https://opendocs.alipay.com/mini/isv/creatminiapp   这个  my.getExtConfigSync()  是三方模板里面的

**Comment by 18657769868** [comment]
my.getAppIdSync()

**Comment by 18657769868** [comment]
my.getUpdateManager()

**Comment by 18657769868** [comment]
my.showSharePanel();
