### ISSUE TITLE
Change to my.scan() arguments

### ISSUE THREAD

**Issue by DillyDallyKing** [ant-mini-program/mini-types#38]
Hi!

Just checking on the alipay documentations for my.scan() https://opendocs.alipay.com/mini/api/scan. I see that there's a change to the argument `type` to `scanType` and the input has changed from `qr` | `barCode` to Array<string> that takes in  ['qrCode','barCode']

Brandon

**Comment by yibuyisheng** [comment]
Ok, Thanks for your reminding. We will correct this.

**Comment by Yaob1990** [comment]
i add some argument type  
[scan](https://github.com/ant-mini-program/mini-types/pull/40/commits/8e2be06ac84f615297330fe04d9aa78d4b22ec2d)

```ts
  /**
   * 扫码识别类型，默认值为 ['qrCode','barCode']
   * 二维码 | 条码 | DM码 | PDF417码 | 窄条二维码 | 异构码
   */
  type IScanType = 'qrCode' | 'barCode' | 'dmCode' | 'pdf417Code' | 'narrowCode' | 'hmCode';
```

**Comment by yibuyisheng** [comment]
fixed
