### ISSUE TITLE
[bug] Duplicate identifier 'Omit'

### ISSUE THREAD

**Issue by Akimotorakiyu** [ant-mini-program/mini-types#6]
typescript version: 3.5.1

![图片](https://user-images.githubusercontent.com/31165554/59002920-a0e59700-8846-11e9-8591-479f5c6c77b4.png)

![图片](https://user-images.githubusercontent.com/31165554/59002958-bb1f7500-8846-11e9-87d7-16bb895dc7f2.png)

**Comment by Phieo** [comment]
fixed 0.0.2
